#!/bin/bash
set -e

if [ -x ".env" ]; then
  set -a
  . ./.env
  set +a
fi;

if [ "$TEST_DATABASE_URL" == "" ]; then
  echo "ERROR: No test database configured; aborting"
  echo
  echo "To resolve this, ensure environmental variable TEST_DATABASE_URL is set"
  exit 1;
fi;

# Import latest schemas (throw on error)
for schema in $(ls __tests__/schemas); do
  psql -Xqv ON_ERROR_STOP=1 -f __tests__/schemas/${schema}/schema.sql "$TEST_DATABASE_URL"
done
echo "Database reset successfully ✅"

# Now run the tests
jest -i $@
